#!/bin/bash

#
# (c) 2010 by David Nies (nies.david@googlemail.com)
#     http://www.twitter.com/Sh4pe
#
# Use of this source code is governed by a license 
# that can be found in the LICENSE file.
#

port=6060

echo "Starting godoc server. Open 127.0.0.1:${port} to see the documentation"
godoc -path="./src/komoku" -http=:$port
